# frozen_string_literal: true

source 'https://rubygems.org'

gem 'pry'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'simplecov-console'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
